In [2]:
import numpy as np

In [13]:
# Q1 create a NumPy array containing integers from 1 to 20. Display the array and its shape, size, and ndim.
array = np.arange(1,21)
print(array.shape)
print(array.ndim)
print(array.size)

(20,)
1
20


In [22]:
# Q2. Create a 2D array (3×4) of random integers between 10 and 99. Display the array and print its dtype, itemsize, and nbytes.
array = np.random.randint(10,100,(3,4))
print(array)
print("type:", array.dtype)
print("size:", array.size)
print("nbytes:", array.nbytes)

[[35 68 72 54]
 [30 67 62 63]
 [74 75 73 22]]
type: int32
size: 12
nbytes: 48


In [41]:
# Q3. Generate the following special arrays: A 5×5 array of zeros, A 4×4 array of ones, A 6×6 identity matrix.
array = np.zeros((5,5))
array2 = np.ones((4,4))
array3 = np.identity(6)
print(array)
print('\n')
print(array2)
print('\n')
print(array3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [46]:
# Q4. Use np.arange to create an array of integers from 0 to 50 with a step of 5. Then use np.linspace to generate 10 evenly spaced values between 0 and 1.
np.arange(0,51,5)
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [66]:
# Q5 Given a 2D array of shape (4,5), perform the following: Extract the first row, Extract the last column, Extract all elements greater than 20.
array = np.random.randint(1,20,(4,5))
print(array)

[[16  4 14  6  9]
 [18 16  6  9 17]
 [ 1  3 17  1  7]
 [ 5  3 12  3 12]]


In [67]:
array[0]


array([16,  4, 14,  6,  9], dtype=int32)

In [74]:
array[:,[4]]

array([[ 9],
       [17],
       [ 7],
       [12]], dtype=int32)

In [86]:
# Q6. Create a 3D NumPy array of shape (2,3,4) filled with random integers. Print its shape and access the element at position [1,2,3].
array = np.random.randint(0,100,size = (2,3,4))
array

array([[[25, 24, 53, 98],
        [69, 41, 19, 22],
        [13, 91, 38, 31]],

       [[24, 14, 81, 29],
        [50, 54, 91, 74],
        [47, 17, 62, 42]]], dtype=int32)

In [118]:
# Q8. Reshape a 1D array of 24 elements into a (4,6) array, then flatten it with ravel() and flatten(). Explain the difference in behavior.
arr = np.arange(1,25)
arr2 = arr.reshape(4,6)
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [122]:
# Q9. Create two arrays and perform the following concatenations: Horizontal stack, Vertical stack, Split the resulting array back into equal parts.
arr1 = np.array([[2,3,4],[1,1,2],[1,2,4]])
arr1
arr2 = np.array([[1,3,2],[2,4,2], [2,2,3]])
arr2

array([[1, 3, 2],
       [2, 4, 2],
       [2, 2, 3]])

In [123]:
np.hstack([arr1,arr2])

array([[2, 3, 4, 1, 3, 2],
       [1, 1, 2, 2, 4, 2],
       [1, 2, 4, 2, 2, 3]])