1. Create a new 5×4 matrix of scores (5 students, 4 subjects). Compute each student’s total 
score and the average per subject. 

In [ ]:
import numpy as np
student_matrix = np.random.randint(70, 101, size=(5, 4))
student_matrix


array([[ 74,  80,  89,  78],
       [100,  83,  84,  85],
       [ 70,  78,  70,  70],
       [ 98,  73,  82,  89],
       [ 82,  91,  77,  91]], dtype=int32)

In [42]:
# student_1_total_score = np.sum(student_matrix[0])
# student_2_total_score = np.sum(student_matrix[1])
# student_3_total_score = np.sum(student_matrix[2])
# student_4_total_score = np.sum(student_matrix[3])
# student_5_total_score = np.sum(student_matrix[4])
# print("-- Student's Total Score--\n")
# print(f"student_1 total score: {student_1_total_score}")
# print(f"student_2 total score: {student_2_total_score}")
# print(f"student_3 total score: {student_3_total_score}")
# print(f"student_4 total score: {student_4_total_score}")
# print(f"student_5 total score: {student_5_total_score}")

In [18]:
student_totals = np.sum(student_matrix, axis=1)
print("-- Student's Total Score--")
for i, total in enumerate(student_totals):
    print(f" student_{i+1} total score: {total}")

-- Student's Total Score--
 student_1 total score: 321
 student_2 total score: 352
 student_3 total score: 288
 student_4 total score: 342
 student_5 total score: 341


In [39]:
student_subject_avgs = np.mean(student_matrix, axis=0)
subjects = ["Mathematics", "English Language", "Chemistry", "Pyhsics"]
print("-- Student's Subjects Average Scores--")
for i, m in enumerate(student_subject_avgs):
    print(f" {subjects[i]} Average: {m}")


-- Student's Subjects Average Scores--
 Mathematics Average: 84.8
 English Language Average: 81.0
 Chemistry Average: 80.4
 Pyhsics Average: 82.6


2. Suppose one subject (e.g., Science) is 3 times more important than others. Apply scalar 
multiplication and recompute totals.

In [26]:
subj_weight = [3,1,1,1]
new_student_matrix = student_matrix * subj_weight

In [27]:
new_student_totals = np.sum(new_student_matrix, axis=1)
print("-- Weighted Student's Total Score--")
for i, total in enumerate(new_student_totals):
    print(f" student_{i+1} total score: {total}")

-- Weighted Student's Total Score--
 student_1 total score: 469
 student_2 total score: 552
 student_3 total score: 428
 student_4 total score: 538
 student_5 total score: 505


3. Define new weights for grading (e.g., 40%, 20%, 30%, 10%). Compute final grades using 
matrix multiplication. 

In [54]:
new_grade_weight = np.array([0.40,0.20,0.30,0.10])
student_matrix_2 = student_matrix * new_grade_weight


In [59]:
print(f"Student Weighted Matrix \n")
print(student_matrix_2)

Student Weighted Matrix 

[[29.6 16.  26.7  7.8]
 [40.  16.6 25.2  8.5]
 [28.  15.6 21.   7. ]
 [39.2 14.6 24.6  8.9]
 [32.8 18.2 23.1  9.1]]


4. Compare Student 3 and Student 4 using vector subtraction. Who performed better in each 
subject?

In [62]:
student_3 = student_matrix[2]
studemt_4 = student_matrix[3]

In [63]:
student_compare = student_3 - studemt_4
student_compare

array([-28,   5, -12, -19], dtype=int32)

In [66]:
subjects = ["Mathematics", "English Language", "Chemistry", "Pyhsics"]
for i, score in enumerate(student_compare):
    if score > 0:
        print(f"Student 3 has {score} marks above Student 4 in test {subjects[i]}")
    elif score < 0:
        print(f"Student 4 has {abs(score)} marks above Student 3 in test {subjects[i]}")
    else:
        print(f"Student 3 and Student 4 scored the same in test {subjects[i]}")


Student 4 has 28 marks above Student 3 in test Mathematics
Student 3 has 5 marks above Student 4 in test English Language
Student 4 has 12 marks above Student 3 in test Chemistry
Student 4 has 19 marks above Student 3 in test Pyhsics
