In [1]:
import numpy as np

In [5]:
A = np.array(
    [
        [2,-1,3],
        [0,4,1]
    ])

B = np.array(
    [
        [1,2],
        [-2,0],
        [5,-3]
    ]
)

In [9]:
print(f"The dimension of Matrix A is {A.shape}")
print(f"The dimension of Matrix B is {B.shape}")


The dimension of Matrix A is (2, 3)
The dimension of Matrix B is (3, 2)


In [46]:
A_row, A_col = A.shape
B_row, B_col = B.shape

In [29]:
print(f"The number of rows in Matrix A is {A_row}")
print(f"The number of columns in Matrix A is {A_col}")

The number of rows in Matrix A is 2
The number of columns in Matrix A is 3


In [30]:
print(f"The number of rows in Matrix B is {B_row}")
print(f"The number of columns in Matrix B is {B_col}")

The number of rows in Matrix B is 3
The number of columns in Matrix B is 2


** Matrix A can multiply Matrix B since the column of A is equal row of B, resulting to a (2,2) Matrix

In [ ]:
A_col == B_row

True

Multiplication of Matrix A and B

In [37]:
AB = np.dot(A,B)
print("Multiplication of Matrix A and B")
print(AB)

Multiplication of Matrix A and B
[[19 -5]
 [-3 -3]]


** Matrix B can also multiply Matrix A since the column of B is equal row of A, resulting to a (3,3) Matrix

In [40]:
B_col == A_row

True

In [39]:
BA = np.dot(B,A)
print("Multiplication of Matrix B and A")
print(BA)

Multiplication of Matrix B and A
[[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
