### Task 1

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 51, size=(6,6))
print(arr)

[[34 12 47  9 16 36]
 [30 37 38  4 12  2]
 [21 13 26 42 35 11]
 [ 3 28  1 12 32 41]
 [ 7 16 44  8 25 48]
 [42  1 33 15 21 40]]


### Task 2

In [3]:
row1 = arr[0]
row2 = arr[1]

print(row1,row2)

[34 12 47  9 16 36] [30 37 38  4 12  2]


In [4]:
first2rows = arr[[0,1]]
print(first2rows)

[[34 12 47  9 16 36]
 [30 37 38  4 12  2]]


In [5]:
last3rows = arr[3:]
print(last3rows)

[[ 3 28  1 12 32 41]
 [ 7 16 44  8 25 48]
 [42  1 33 15 21 40]]


In [6]:
even_no = arr[arr % 2 == 0]
even_no

array([34, 12, 16, 36, 30, 38,  4, 12,  2, 26, 42, 28, 12, 32, 16, 44,  8,
       48, 42, 40], dtype=int32)

In [7]:
even_no_matrix = np.where(arr % 2 == 0, arr, 0)
even_no_matrix

array([[34, 12,  0,  0, 16, 36],
       [30,  0, 38,  4, 12,  2],
       [ 0,  0, 26, 42,  0,  0],
       [ 0, 28,  0, 12, 32,  0],
       [ 0, 16, 44,  8,  0, 48],
       [42,  0,  0,  0,  0, 40]], dtype=int32)

### Task 3

In [8]:
arr_reshape = arr.reshape(3,2,6)
arr_reshape

array([[[34, 12, 47,  9, 16, 36],
        [30, 37, 38,  4, 12,  2]],

       [[21, 13, 26, 42, 35, 11],
        [ 3, 28,  1, 12, 32, 41]],

       [[ 7, 16, 44,  8, 25, 48],
        [42,  1, 33, 15, 21, 40]]], dtype=int32)

In [9]:
arr_flatten = arr.flatten()
arr_flatten

array([34, 12, 47,  9, 16, 36, 30, 37, 38,  4, 12,  2, 21, 13, 26, 42, 35,
       11,  3, 28,  1, 12, 32, 41,  7, 16, 44,  8, 25, 48, 42,  1, 33, 15,
       21, 40], dtype=int32)

### Task 4

In [10]:
arr_2 = np.eye(4)
print("4x4 identity matrix")
print(arr_2)

4x4 identity matrix
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
arr_3 = np.diag(np.arange(10,50,10))
print("diagonal matix")
print(arr_3)

diagonal matix
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


### Task 5

In [12]:
matrix_1 = np.random.randint(1,10, size=(3,4))
matrix_2 = np.random.randint(1,10, size=(4,3))
print("First Matrix")
print(matrix_1)
print("\nSecond Matrix")
print(matrix_2)


First Matrix
[[9 1 7 1]
 [9 3 9 2]
 [7 6 8 5]]

Second Matrix
[[3 2 3]
 [6 9 2]
 [5 5 9]
 [8 5 6]]


In [13]:
result = np.dot(matrix_1,matrix_2)
print(f"Matrix Multiplictaion/n" )
print(result)


Matrix Multiplictaion/n
[[ 76  67  98]
 [106 100 126]
 [137 133 135]]


### Task 6

In [45]:
def square_of_numbers(arr):
    square = arr.copy()
    square_no = np.where(square % 2 == 0, square ** 2, -1)
    return square_no

In [ ]:

rows = int(input("Enter the number of rows: "))
columns = int(input("Enter the number of columns: "))

matrix = []
for i in range(rows):
    row = []
    for j in range(columns):
        element = int(input(f"Enter element [{i}][{j}]"))
        row.append(element)
    matrix.append(row)


In [47]:
arr = np.array(matrix)
new_arr = square_of_numbers(arr)

print("User Matrx\n")
print(arr)
print("\nSquare of even elemet in user Matrix with odd numbers replaced")
print(new_arr)


User Matrx

[[1 2 0 1]
 [2 1 4 5]
 [2 1 2 3]]

Square of even elemet in user Matrix with odd numbers replaced
[[-1  4  0 -1]
 [ 4 -1 16 -1]
 [ 4 -1  4 -1]]
